# Generated by Django 3.1.4 on 2020-12-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True)),
                ('nickname', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
