# Generated by Django 3.1.4 on 2020-12-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_nbateam'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='nba_api_id',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbateam',
            name='abbreviation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='nba_api_id',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbateam',
            name='state',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='year_founded',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NBAGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='nba.nbateam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='nba.nbateam')),
            ],
        ),
    ]
