# Generated by Django 3.1.4 on 2021-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_auto_20201222_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='number',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='position_1',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='position_2',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='school',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
