# Generated by Django 3.1.4 on 2021-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_auto_20210106_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
