# Generated by Django 3.1.4 on 2021-01-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_auto_20210107_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nbaplayer',
            options={'verbose_name': 'NBA Player', 'verbose_name_plural': 'NBA Players'},
        ),
    ]
