# Generated by Django 3.1.4 on 2021-01-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_nbagame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbagame',
            old_name='nba_api_aid',
            new_name='nba_api_id',
        ),
    ]
