# Generated by Django 3.1.4 on 2021-01-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_nbateamgamelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateamgamelog',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_gamelogs', related_query_name='team_gamelog', to='nba.nbagame'),
        ),
        migrations.AlterField(
            model_name='nbateamgamelog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_gamelogs', related_query_name='team_gamelog', to='nba.nbateam'),
        ),
    ]
